### ISSUE TITLE
AdWords layout fix

### ISSUE THREAD

**Issue by lucianosousa** [call4paperz/call4paperz#227]
needs center it

Home
![screen shot 2017-10-25 at 20 02 13](https://user-images.githubusercontent.com/44833/32025567-81f52f88-b9bf-11e7-8af4-abb2a8439b1d.png)

Events page
![screen shot 2017-10-25 at 20 01 53](https://user-images.githubusercontent.com/44833/32025582-8c44516c-b9bf-11e7-80ff-a5828fa76f42.png)

**Comment by tauil** [comment]
I've fixed it on the new layout coming soon. I can fix this if no one picks it.

**Comment by lucianosousa** [comment]
go ahead

**Comment by jeansflores** [comment]
I think this issue has already been fixed

**Comment by lucianosousa** [comment]
@jeansflores footer one is fine, but the ad after the events list is still broken

<img width="999" alt="Screen Shot 2019-10-07 at 11 27 12 AM" src="https://user-images.githubusercontent.com/44833/66325574-7c352500-e8f5-11e9-9e9d-bde15f03be40.png">

**Comment by frankyston** [comment]
PR with fix: https://github.com/call4paperz/call4paperz/pull/348
